"""picture and bio fields added to User model

Revision ID: 20652cb05fb9
Revises: 
Create Date: 2024-07-22 02:47:56.665823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20652cb05fb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=520), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
